baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
canonifyURLs = true
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
highlight_theme = "tomorrow-night"
reveal_cdn = "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0"
